// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPsasqHwvqzjmT4gpB1Wjs3D11dvkoNQ8',
    appId: '1:4218641434:ios:72ef63bacc6b90fd3b05a3',
    messagingSenderId: '4218641434',
    projectId: 'ecommerceapp-60ad9',
    storageBucket: 'ecommerceapp-60ad9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHcLDAMWA8wDEeoaxxTe8rA8lfuZprsO8',
    appId: '1:4218641434:web:3355d6c7f8f867333b05a3',
    messagingSenderId: '4218641434',
    projectId: 'ecommerceapp-60ad9',
    authDomain: 'ecommerceapp-60ad9.firebaseapp.com',
    storageBucket: 'ecommerceapp-60ad9.firebasestorage.app',
    measurementId: 'G-NZ83YJ64FP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHcLDAMWA8wDEeoaxxTe8rA8lfuZprsO8',
    appId: '1:4218641434:web:3355d6c7f8f867333b05a3',
    messagingSenderId: '4218641434',
    projectId: 'ecommerceapp-60ad9',
    authDomain: 'ecommerceapp-60ad9.firebaseapp.com',
    storageBucket: 'ecommerceapp-60ad9.firebasestorage.app',
    measurementId: 'G-NZ83YJ64FP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPsasqHwvqzjmT4gpB1Wjs3D11dvkoNQ8',
    appId: '1:4218641434:ios:72ef63bacc6b90fd3b05a3',
    messagingSenderId: '4218641434',
    projectId: 'ecommerceapp-60ad9',
    storageBucket: 'ecommerceapp-60ad9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqiCl4VAGPpztSREb_-vkirhZbqcMZlXc',
    appId: '1:4218641434:android:57f8014aa8ed8ce23b05a3',
    messagingSenderId: '4218641434',
    projectId: 'ecommerceapp-60ad9',
    storageBucket: 'ecommerceapp-60ad9.firebasestorage.app',
  );

}